=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/dtd/Accounting.dtd
<!ELEMENT Accounting (name, Accounts,Journals,Balances?,CounterParties?,Statements?,Mortgages?)>
<!ELEMENT Accounts (name)>
<!ELEMENT Journals (name)>
<!ELEMENT Balances (name)>
<!ELEMENT Mortgages (name)>
<!ELEMENT CounterParties (name)>
<!ELEMENT Statements (name)>
<!ELEMENT name (#PCDATA)>

=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/xml/Accountings/Tay 2013.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../xsl/Accounting2xml.xsl"?>
<!DOCTYPE Accounting SYSTEM "../../dtd/Accounting.dtd">
<Accounting>
  <name>Tay 2013</name>
  <Accounts>
    <name>Accounts</name>
  </Accounts>
  <Journals>
    <name>Journals</name>
  </Journals>
  <Balances>
    <name>Balances</name>
  </Balances>
  <CounterParties>
    <name>CounterParties</name>
  </CounterParties>
  <Statements>
    <name>Statements</name>
  </Statements>
  <Mortgages>
    <name>Mortgages</name>
  </Mortgages>
</Accounting>
