=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/dtd/Journal.dtd
<!ELEMENT Journal (abbr,name,type,Transaction*,CurrentObject)>
<!ELEMENT Transaction (date,description?,id,Booking*)>
<!ELEMENT Booking ((Account|Mortgage),Movement)>
<!ELEMENT Movement ((debit|credit),id)>
<!ELEMENT abbr (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT Account (#PCDATA)>
<!ELEMENT Mortgage (#PCDATA)>
<!ELEMENT debit (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT CurrentObject (#PCDATA)>

=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/xml/Accountings/Thuis 2012/Journals/Transfer.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Journal SYSTEM "../../../../dtd/Journal.dtd">
<Journal>
  <abbr>TRF</abbr>
  <name>Transfer</name>
  <type>default</type>
  <Transaction>
    <date>27/9/2012</date>
    <id>1</id>
  <Booking>
    <Account>Bank Tay</Account>
  <Movement>
    <debit>101.00</debit>
    <id>1978</id>
  </Movement>
  </Booking>
  <Booking>
    <Account>Bank David</Account>
  <Movement>
    <credit>101.00</credit>
    <id>1979</id>
  </Movement>
  </Booking>
  </Transaction>
  <Transaction>
    <date>2/10/2012</date>
    <id>2</id>
  <Booking>
    <Account>Bank Tay</Account>
  <Movement>
    <debit>170.00</debit>
    <id>1980</id>
  </Movement>
  </Booking>
  <Booking>
    <Account>Bank Dara</Account>
  <Movement>
    <credit>170.00</credit>
    <id>1981</id>
  </Movement>
  </Booking>
  </Transaction>
  <Transaction>
    <date>19/10/2012</date>
    <id>3</id>
  <Booking>
    <Account>Bank Dara</Account>
  <Movement>
    <debit>300.00</debit>
    <id>1982</id>
  </Movement>
  </Booking>
  <Booking>
    <Account>Bank Tay</Account>
  <Movement>
    <credit>300.00</credit>
    <id>1983</id>
  </Movement>
  </Booking>
  </Transaction>
  <Transaction>
    <date>5/11/2012</date>
    <id>4</id>
  <Booking>
    <Account>Bank Tay</Account>
  <Movement>
    <debit>100.00</debit>
    <id>1984</id>
  </Movement>
  </Booking>
  <Booking>
    <Account>Bank Dara</Account>
  <Movement>
    <credit>100.00</credit>
    <id>1985</id>
  </Movement>
  </Booking>
  </Transaction>
  <Transaction>
    <date>30/11/2012</date>
    <id>5</id>
  <Booking>
    <Account>Bank Tay</Account>
  <Movement>
    <debit>1200.00</debit>
    <id>1986</id>
  </Movement>
  </Booking>
  <Booking>
    <Account>Bank Dara</Account>
  <Movement>
    <credit>1200.00</credit>
    <id>1987</id>
  </Movement>
  </Booking>
  </Transaction>
    <CurrentObject>null</CurrentObject>
</Journal>
