=== DavidCADanneels/Accounting/src/main/resources/dtd/Account.dtd
<!ELEMENT Account (name,action*,closed?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT action (nr,journal_xml,journal_html,date,debit?,credit?,description)>
<!ELEMENT nr (#PCDATA)>
<!ELEMENT journal_xml (#PCDATA)>
<!ELEMENT journal_html (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT debit (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT closed (debitTotal,creditTotal,saldo)>
<!ELEMENT debitTotal (#PCDATA)>
<!ELEMENT creditTotal (#PCDATA)>
<!ELEMENT saldo (#PCDATA)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST closed type CDATA #REQUIRED>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Thuis 2012/Accounts/Telefoonkosten.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "../../../dtd/Account.dtd">
<Account>
  <name>Telefoonkosten</name>
  <action id="24">
    <nr>DIV24</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>30/1/2012</date>
    <debit>362.96</debit>
    <description>101103438942650</description>
  </action>
  <action id="68">
    <nr>DIV68</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>27/2/2012</date>
    <debit>277.03</debit>
    <description>101103438942751</description>
  </action>
  <action id="136">
    <nr>DIV136</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>5/4/2012</date>
    <debit>15.00</debit>
    <description>101011047087496</description>
  </action>
  <action id="140">
    <nr>DIV140</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>5/4/2012</date>
    <debit>161.26</debit>
    <description>101103438942852</description>
  </action>
  <action id="166">
    <nr>DIV166</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>24/4/2012</date>
    <debit>222.77</debit>
    <description>101103438942953</description>
  </action>
  <action id="226">
    <nr>DIV226</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>29/5/2012</date>
    <debit>120.54</debit>
    <description>101103438943054</description>
  </action>
  <action id="409">
    <nr>DIV409</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>20/8/2012</date>
    <debit>12.31</debit>
    <description>KCLEU326995305</description>
  </action>
  <action id="418">
    <nr>DIV418</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>28/8/2012</date>
    <debit>280.01</debit>
    <description>10343894</description>
  </action>
  <action id="455">
    <nr>DIV455</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>19/9/2012</date>
    <debit>182.65</debit>
    <description>101103438943458</description>
  </action>
  <action id="456">
    <nr>DIV456</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>19/9/2012</date>
    <debit>196.06</debit>
    <description>10343894</description>
  </action>
  <action id="497">
    <nr>DIV497</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>15/10/2012</date>
    <debit>12.31</debit>
    <description>KCLEU326995305</description>
  </action>
  <action id="514">
    <nr>DIV514</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>30/10/2012</date>
    <debit>360.93</debit>
    <description>101103438943559</description>
  </action>
  <action id="551">
    <nr>DIV551</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>23/11/2012</date>
    <debit>222.67</debit>
    <description>101103438943660</description>
  </action>
  <action id="606">
    <nr>DIV606</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>21/12/2012</date>
    <debit>242.91</debit>
    <description>Proximus</description>
  </action>
  <closed type = "debit">
    <debitTotal>2669.41</debitTotal>
    <creditTotal>0.00</creditTotal>
    <saldo>2669.41</saldo>
  </closed>
</Account>

=== DavidCADanneels/Accounting/src/main/resources/xml/Thuis 2012/Accounts/Energiekosten.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xsl\Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\dtd\Account.dtd">
<Account>
  <name>Energiekosten</name>
  <action id="532">
    <nr>DIV532</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>6/11/2012</date>
    <debit>600.00</debit>
    <description>voorgeschoten door ma: dokter-apotheek-gas-electriciteit</description>
  </action>
  <closed type = "debit">
    <debitTotal>600.00</debitTotal>
    <creditTotal>0.00</creditTotal>
    <saldo>600.00</saldo>
  </closed>
</Account>

=== DavidCADanneels/Accounting/src/main/resources/xml/Thuis 2012/Accounts/Post Dara.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xsl\Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\dtd\Account.dtd">
<Account>
  <name>Post Dara</name>
  <action id="5">
    <nr>DIV5</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>10/1/2012</date>
    <debit>100.00</debit>
    <description>storting</description>
  </action>
  <action id="11">
    <nr>DIV11</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>17/1/2012</date>
    <debit>100.00</debit>
    <description>storting</description>
  </action>
  <action id="17">
    <nr>DIV17</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>20/1/2012</date>
    <debit>113.54</debit>
    <description>storting</description>
  </action>
  <action id="31">
    <nr>DIV31</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>3/2/2012</date>
    <debit>312.86</debit>
    <description>storting</description>
  </action>
  <action id="53">
    <nr>DIV53</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>17/2/2012</date>
    <debit>202.49</debit>
    <description>storting</description>
  </action>
  <action id="64">
    <nr>DIV64</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>24/2/2012</date>
    <debit>214.02</debit>
    <description>storting</description>
  </action>
  <action id="76">
    <nr>DIV76</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>2/3/2012</date>
    <debit>113.23</debit>
    <description>storting</description>
  </action>
  <action id="100">
    <nr>DIV100</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>16/3/2012</date>
    <debit>203.60</debit>
    <description>storting</description>
  </action>
  <action id="118">
    <nr>DIV118</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>23/3/2012</date>
    <debit>130.00</debit>
    <description>storting</description>
  </action>
  <action id="157">
    <nr>DIV157</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>17/4/2012</date>
    <debit>440.00</debit>
    <description>storting</description>
  </action>
  <action id="174">
    <nr>DIV174</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>29/4/2012</date>
    <debit>100.00</debit>
    <description>storting</description>
  </action>
  <action id="309">
    <nr>DIV309</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>5/7/2012</date>
    <debit>300.00</debit>
    <description>storting</description>
  </action>
  <action id="339">
    <nr>DIV339</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>18/7/2012</date>
    <debit>190.96</debit>
    <description>storting</description>
  </action>
  <action id="411">
    <nr>DIV411</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>21/8/2012</date>
    <debit>286.18</debit>
    <description>storting</description>
  </action>
  <action id="419">
    <nr>DIV419</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>28/8/2012</date>
    <credit>100.00</credit>
    <description>Afhaling</description>
  </action>
  <action id="448">
    <nr>DIV448</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>13/9/2012</date>
    <debit>100.00</debit>
    <description>storting</description>
  </action>
  <action id="478">
    <nr>DIV478</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>3/10/2012</date>
    <credit>2200.00</credit>
    <description>aankoop tickets februari</description>
  </action>
  <action id="484">
    <nr>DIV484</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>7/10/2012</date>
    <debit>100.00</debit>
    <description>
  </description>
  </action>
  <action id="535">
    <nr>DIV535</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>6/11/2012</date>
    <credit>700.00</credit>
    <description>
  </description>
  </action>
  <action id="601">
    <nr>DIV601</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>18/12/2012</date>
    <debit>2500.00</debit>
    <description>overschot feestje</description>
  </action>
  <closed type = "debit">
    <debitTotal>5506.88</debitTotal>
    <creditTotal>3000.00</creditTotal>
    <saldo>2506.88</saldo>
  </closed>
</Account>

=== DavidCADanneels/Accounting/src/main/resources/xml/Thuis 2012/Accounts/Vakantiegeld David.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xsl\Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\dtd\Account.dtd">
<Account>
  <name>Vakantiegeld David</name>
  <action id="229">
    <nr>DIV229</nr>
    <journal_xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals\Diversen.xml</journal_xml>
    <journal_html>null</journal_html>
    <date>31/5/2012</date>
    <credit>190.71</credit>
    <description>/A/ 91RLMJ11 Vakantiegeld 2012</description>
  </action>
  <closed type = "credit">
    <debitTotal>0.00</debitTotal>
    <creditTotal>190.71</creditTotal>
    <saldo>190.71</saldo>
  </closed>
</Account>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Thuis 2012/Accounts/Spaar David.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../xsl/Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "../../dtd/Account.dtd">
<Account>
  <name>Spaar David</name>
  <action id="1">
    <nr>DIV1</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>1/1/2012</date>
    <debit>0.23</debit>
    <description>beginbalans</description>
  </action>
  <action id="2">
    <nr>DIV2</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>1/1/2012</date>
    <debit>0.01</debit>
    <description>intresten</description>
  </action>
  <action id="173">
    <nr>DIV173</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>29/4/2012</date>
    <debit>2000.00</debit>
    <description>
  </description>
  </action>
  <action id="216">
    <nr>DIV216</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>23/5/2012</date>
    <debit>600.00</debit>
    <description>
  </description>
  </action>
  <action id="219">
    <nr>DIV219</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>27/5/2012</date>
    <credit>2000.00</credit>
    <description>
  </description>
  </action>
  <action id="283">
    <nr>DIV283</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>23/6/2012</date>
    <debit>600.00</debit>
    <description>
  </description>
  </action>
  <action id="286">
    <nr>DIV286</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>25/6/2012</date>
    <credit>500.00</credit>
    <description>
  </description>
  </action>
  <action id="327">
    <nr>DIV327</nr>
    <journal_xml>../Journals/Diversen.xml</journal_xml>
    <journal_html>../Journals/Diversen.html</journal_html>
    <date>12/7/2012</date>
    <credit>700.00</credit>
    <description>
  </description>
  </action>
  <closed type = "debit">
    <debitTotal>3200.24</debitTotal>
    <creditTotal>3200.00</creditTotal>
    <saldo>0.24</saldo>
  </closed>
</Account>
