=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/dtd/Accounting.dtd
<!ELEMENT Accounting (name,Accounts,Mortgages?,Journals,Balances,CounterParties?,Statements?)>
<!ELEMENT Accounts (name)>
<!ELEMENT Journals (name)>
<!ELEMENT Balances (name)>
<!ELEMENT Mortgages (name)>
<!ELEMENT CounterParties (name)>
<!ELEMENT Statements (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT xml (#PCDATA)>
<!ELEMENT html (#PCDATA)>
<!ELEMENT xmlFolder (#PCDATA)>
<!ELEMENT htmlFolder (#PCDATA)>

=== DavidCADanneels/Accounting/src/main/resources/xml/Thuis 2012/Accounting.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xsl\Accounting2xml.xsl"?>
<!DOCTYPE Accounting SYSTEM "C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\dtd\Accounting.dtd">
<Accounting>
  <name>Thuis 2012</name>
  <Accounts>
    <name>Accounts</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Accounts.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Accounts</xmlFolder>
  </Accounts>
  <Mortgages>
    <name>Mortgages</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Mortgages.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Mortgages</xmlFolder>
  </Mortgages>
  <Journals>
    <name>Journals</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Journals</xmlFolder>
  </Journals>
  <Balances>
    <name>Balances</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Balances.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Balances</xmlFolder>
  </Balances>
  <CounterParties>
    <name>CounterParties</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\CounterParties.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\CounterParties</xmlFolder>
  </CounterParties>
  <Statements>
    <name>Statements</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Statements.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Thuis 2012\Statements</xmlFolder>
  </Statements>
</Accounting>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Test/Accounting.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xsl/Accounting2xml.xsl"?>
<!DOCTYPE Accounting SYSTEM "/home/david/workspace/Accounting/BasicAccounting/src/main/resources/dtd/Accounting.dtd">
<Accounting>
  <name>Test</name>
  <Accounts>
    <name>Accounts</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Accounts.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Accounts</xmlFolder>
  </Accounts>
  <Mortgages>
    <name>Mortgages</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Mortgages.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Mortgages</xmlFolder>
  </Mortgages>
  <Journals>
    <name>Journals</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Journals.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Journals</xmlFolder>
  </Journals>
  <Balances>
    <name>Balances</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Balances.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Balances</xmlFolder>
  </Balances>
  <CounterParties>
    <name>CounterParties</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/CounterParties.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/CounterParties</xmlFolder>
  </CounterParties>
  <Statements>
    <name>Statements</name>
    <xml>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Statements.xml</xml>
    <xmlFolder>/home/david/workspace/Accounting/BasicAccounting/src/main/resources/xml/Test/Statements</xmlFolder>
  </Statements>
</Accounting>

=== DavidCADanneels/Accounting/src/main/resources/xml/Test/Accounting.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xsl\Accounting2xml.xsl"?>
<!DOCTYPE Accounting SYSTEM "C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\dtd\Accounting.dtd">
<Accounting>
  <name>Test</name>
  <Accounts>
    <name>Accounts</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Accounts.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Accounts</xmlFolder>
  </Accounts>
  <Mortgages>
    <name>Mortgages</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Mortgages.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Mortgages</xmlFolder>
  </Mortgages>
  <Journals>
    <name>Journals</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Journals.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Journals</xmlFolder>
  </Journals>
  <Balances>
    <name>Balances</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Balances.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Balances</xmlFolder>
  </Balances>
  <CounterParties>
    <name>CounterParties</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\CounterParties.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\CounterParties</xmlFolder>
  </CounterParties>
  <Statements>
    <name>Statements</name>
    <xml>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Statements.xml</xml>
    <xmlFolder>C:\Users\Dafke\workspace\trunk\Accounting\src\main\resources\xml\Test\Statements</xmlFolder>
  </Statements>
</Accounting>
