=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/dtd/Accounts.dtd
<!ELEMENT Accounts ((Account*,Mortgage*)*,CurrentObject?)>
<!ELEMENT Account (name,type)>
<!ELEMENT Mortgage (CapitalAccountHtml?,CapitalAccountName?,CapitalAccountXml?,IntrestAccountHtml?,IntrestAccountName?,IntrestAccountXml?,name,nrPayed,total,type)>
<!ELEMENT xml (#PCDATA)>
<!ELEMENT html (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT nrPayed (#PCDATA)>
<!ELEMENT CapitalAccountName (#PCDATA)>
<!ELEMENT CapitalAccountXml (#PCDATA)>
<!ELEMENT CapitalAccountHtml (#PCDATA)>
<!ELEMENT IntrestAccountName (#PCDATA)>
<!ELEMENT IntrestAccountXml (#PCDATA)>
<!ELEMENT IntrestAccountHtml (#PCDATA)>
<!ELEMENT CurrentObject (#PCDATA)>

=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/xml/Accountings/Thuis 2016/Accounts.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Accounts SYSTEM "../../../dtd/Accounts.dtd">
<Accounts>
  <name>Accounts</name>
  <Account>
    <defaultAmount>28.12</defaultAmount>
    <name>AXA-Bijstandsverzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>36.44</defaultAmount>
    <name>AXA-Brandverzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>AXA-BrommerVerzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>57.12</defaultAmount>
    <name>AXA-Levensverzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>50.57</defaultAmount>
    <name>AXA-MotoVerzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Action</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Aldi</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Allerlei</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Apotheek</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Aqualibi</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Auto</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Bank Dara</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Bank David</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Bank Tay</name>
    <type>Asset</type>
  </Account>
  <Account>
    <defaultAmount>3.50</defaultAmount>
    <name>Bankkosten</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Bart Smit</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Belastingen</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Benzine</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Biberium</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Bibliotheek</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Blokker</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Boetes</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Brantano</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Brico</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Brico Plan-IT</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Bunrot</name>
    <type>Debit</type>
  </Account>
  <Account>
    <name>Buurtslagers</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>C en A</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>18.57</defaultAmount>
    <name>CM</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Carrefour</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Cash</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Cash-gab</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Colruyt</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Corona Electro</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>32.67</defaultAmount>
    <name>DAS-Autoverzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>DAS-Bijstandsverzekering</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Delhaize</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Diepvries</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Dokter</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Domino Pizza</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>487.60</defaultAmount>
    <name>EDM Sanitair</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Eandis</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Eco-cheques</name>
    <type>Asset</type>
  </Account>
  <Account>
    <defaultAmount>73.77</defaultAmount>
    <name>Essent</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Film</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>19.99</defaultAmount>
    <name>Fitness</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Frietkot</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Giften UK</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Glamodiosa</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>H en M</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Hema</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Huis</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Hypotheek</name>
    <type>Debit</type>
  </Account>
  <Account>
    <name>ICI Paris XL</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>INNO</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Intrest Huis</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Intrest Lening Tay</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Intrest Verbouwing</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>JBC</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>150.00</defaultAmount>
    <name>Kamp Kazou</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Kapitaal</name>
    <type>Liability</type>
  </Account>
  <Account>
    <name>Kapitaal Tay</name>
    <type>Liability</type>
  </Account>
  <Account>
    <name>KinderOpvang</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>273.06</defaultAmount>
    <name>Kindergeld</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Kledij</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Kosten Werk</name>
    <type>Credit</type>
  </Account>
  <Account>
    <name>Kringwinkel</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Kruidvat</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>L en L</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Leenbakker</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Lening Tay</name>
    <type>Debit</type>
  </Account>
  <Account>
    <name>Lening Verbouwing</name>
    <type>Debit</type>
  </Account>
  <Account>
    <defaultAmount>19.35</defaultAmount>
    <name>Lenzen</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Libertys</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Lidl</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Lunch Italian</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>8.45</defaultAmount>
    <name>Lunch Johnsons Control</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Maaltijdcheques Dara</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Maaltijdcheques David</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Maaltijdcheques Tay</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Markt</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Media markt</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Medische kosten</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Music Tay</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Netto Dara</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Netto David</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Netto Tay</name>
    <type>Revenue</type>
  </Account>
  <Account>
    <name>Nightshop Biekorf</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Nightshop FEFA</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Onbekend</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>4.75</defaultAmount>
    <name>Ontbijt</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Parking</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>400.00</defaultAmount>
    <name>Pi Maew</name>
    <type>Debit</type>
  </Account>
  <Account>
    <defaultAmount>6.00</defaultAmount>
    <name>Pitta Diegem</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Pizzahut</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Post Dara</name>
    <type>Asset</type>
  </Account>
  <Account>
    <name>Premaman</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Primo</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Pro-duo</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Quick</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Reis Thailand</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Renmans</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Restaurant</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>School</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>School Tay</name>
    <type>Cost</type>
  </Account>
  <Account>
    <defaultAmount>200.00</defaultAmount>
    <name>Schulden aan ma</name>
    <type>Debit</type>
  </Account>
  <Account>
    <name>Six Nations</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Sluis</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Smatch</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Spaar David</name>
    <type>Asset</type>
  </Account>
  <Account>
    <defaultAmount>200.00</defaultAmount>
    <name>Spaar Sophia</name>
    <type>Asset</type>
  </Account>
  <Account>
    <defaultAmount>9.99</defaultAmount>
    <name>Spotify</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Tandarts</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Telenet</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Thai Shop Brugge</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Thai Shop Lichtervelde</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Thailand</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Ticket Tay</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Torfs</name>
    <type>Cost</type>
  </Account>
  <Account>
    <name>Transactiekosten</name>
    <type>Cost</type>
