=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/dtd/Account.dtd
<!ELEMENT Account (name,action*,closed?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT action (nr,journal,date,debit?,credit?,description)>
<!ELEMENT nr (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT debit (#PCDATA)>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT closed (debitTotal,creditTotal,saldo)>
<!ELEMENT debitTotal (#PCDATA)>
<!ELEMENT creditTotal (#PCDATA)>
<!ELEMENT saldo (#PCDATA)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST closed type CDATA #REQUIRED>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Thuis 2013/Accounts/AXA-Autoverzekering.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "../../../dtd/Account.dtd">
<Account>
  <name>AXA-Autoverzekering</name>
  <action id="16">
    <nr>DIV16</nr>
    <journal>Diversen</journal>
    <date>4/1/2013</date>
    <debit>25.93</debit>
    <description>Verzekeringen januari</description>
  </action>
  <action id="69">
    <nr>DIV69</nr>
    <journal>Diversen</journal>
    <date>6/2/2013</date>
    <debit>25.93</debit>
    <description>verzekeringen + Sophia</description>
  </action>
</Account>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Accountings/Thuis 2013/Accounts/Consumptie.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../../../xsl/Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "../../../../dtd/Account.dtd">
<Account>
  <Movement>
    <date>2/1/2013</date>
    <debit>40.00</debit>
    <description>2/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV4</nr>
  </Movement>
  <Movement>
    <date>3/1/2013</date>
    <debit>49.95</debit>
    <description>3/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV13</nr>
  </Movement>
  <Movement>
    <date>3/1/2013</date>
    <debit>24.95</debit>
    <description>3/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV14</nr>
  </Movement>
  <Movement>
    <date>3/1/2013</date>
    <debit>2.40</debit>
    <description>3/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV15</nr>
  </Movement>
  <Movement>
    <date>4/1/2013</date>
    <debit>59.48</debit>
    <description>4/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV17</nr>
  </Movement>
  <Movement>
    <date>4/1/2013</date>
    <debit>9.09</debit>
    <description>4/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV18</nr>
  </Movement>
  <Movement>
    <date>9/1/2013</date>
    <debit>43.64</debit>
    <description>9/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV20</nr>
  </Movement>
  <Movement>
    <date>9/1/2013</date>
    <debit>40.00</debit>
    <description>9/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV21</nr>
  </Movement>
  <Movement>
    <date>11/1/2013</date>
    <debit>64.12</debit>
    <description>11/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV22</nr>
  </Movement>
  <Movement>
    <date>11/1/2013</date>
    <debit>16.06</debit>
    <description>11/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV23</nr>
  </Movement>
  <Movement>
    <date>11/1/2013</date>
    <debit>76.49</debit>
    <description>11/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV24</nr>
  </Movement>
  <Movement>
    <date>12/1/2013</date>
    <debit>42.30</debit>
    <description>12/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV25</nr>
  </Movement>
  <Movement>
    <date>14/1/2013</date>
    <debit>57.25</debit>
    <description>14/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV26</nr>
  </Movement>
  <Movement>
    <date>15/1/2013</date>
    <debit>50.00</debit>
    <description>15/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV27</nr>
  </Movement>
  <Movement>
    <date>15/1/2013</date>
    <debit>6.90</debit>
    <description>15/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV28</nr>
  </Movement>
  <Movement>
    <date>16/1/2013</date>
    <debit>20.00</debit>
    <description>16/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV30</nr>
  </Movement>
  <Movement>
    <date>17/1/2013</date>
    <debit>64.60</debit>
    <description>17/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV32</nr>
  </Movement>
  <Movement>
    <date>18/1/2013</date>
    <debit>80.00</debit>
    <description>18/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV37</nr>
  </Movement>
  <Movement>
    <date>18/1/2013</date>
    <debit>10.00</debit>
    <description>18/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV37</nr>
  </Movement>
  <Movement>
    <date>18/1/2013</date>
    <debit>40.00</debit>
    <description>18/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV38</nr>
  </Movement>
  <Movement>
    <date>18/1/2013</date>
    <debit>75.41</debit>
    <description>18/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV39</nr>
  </Movement>
  <Movement>
    <date>19/1/2013</date>
    <debit>18.40</debit>
    <description>19/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV40</nr>
  </Movement>
  <Movement>
    <date>19/1/2013</date>
    <debit>59.02</debit>
    <description>19/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV41</nr>
  </Movement>
  <Movement>
    <date>19/1/2013</date>
    <debit>33.58</debit>
    <description>19/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV42</nr>
  </Movement>
  <Movement>
    <date>20/1/2013</date>
    <debit>100.00</debit>
    <description>20/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV43</nr>
  </Movement>
  <Movement>
    <date>22/1/2013</date>
    <debit>20.00</debit>
    <description>22/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV44</nr>
  </Movement>
  <Movement>
    <date>24/1/2013</date>
    <debit>7.73</debit>
    <description>24/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV45</nr>
  </Movement>
  <Movement>
    <date>25/1/2013</date>
    <debit>56.06</debit>
    <description>25/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV46</nr>
  </Movement>
  <Movement>
    <date>25/1/2013</date>
    <debit>47.10</debit>
    <description>25/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV47</nr>
  </Movement>
  <Movement>
    <date>25/1/2013</date>
    <debit>10.83</debit>
    <description>25/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV48</nr>
  </Movement>
  <Movement>
    <date>26/1/2013</date>
    <debit>42.23</debit>
    <description>26/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV49</nr>
  </Movement>
  <Movement>
    <date>26/1/2013</date>
    <debit>44.70</debit>
    <description>26/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV50</nr>
  </Movement>
  <Movement>
    <date>28/1/2013</date>
    <debit>6.28</debit>
    <description>28/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV53</nr>
  </Movement>
  <Movement>
    <date>29/1/2013</date>
    <debit>40.00</debit>
    <description>29/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV54</nr>
  </Movement>
  <Movement>
    <date>30/1/2013</date>
    <debit>128.90</debit>
    <description>30/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV55</nr>
  </Movement>
  <Movement>
    <date>30/1/2013</date>
    <debit>30.40</debit>
    <description>30/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV56</nr>
  </Movement>
  <Movement>
    <date>30/1/2013</date>
    <debit>62.07</debit>
    <description>30/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV57</nr>
  </Movement>
  <Movement>
    <date>2/2/2013</date>
    <debit>40.00</debit>
    <description>2/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV61</nr>
  </Movement>
  <Movement>
    <date>3/2/2013</date>
    <debit>70.02</debit>
    <description>3/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV62</nr>
  </Movement>
  <Movement>
    <date>3/2/2013</date>
    <debit>50.00</debit>
    <description>3/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV63</nr>
  </Movement>
  <Movement>
    <date>4/2/2013</date>
    <debit>63.00</debit>
    <description>4/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV66</nr>
  </Movement>
  <Movement>
    <date>8/2/2013</date>
    <debit>42.91</debit>
    <description>8/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV74</nr>
  </Movement>
  <Movement>
    <date>9/2/2013</date>
    <debit>70.94</debit>
    <description>9/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV75</nr>
  </Movement>
  <Movement>
    <date>11/2/2013</date>
    <debit>16.10</debit>
    <description>11/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV76</nr>
  </Movement>
  <Movement>
    <date>12/2/2013</date>
    <debit>1.20</debit>
    <description>12/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV78</nr>
  </Movement>
  <Movement>
    <date>12/2/2013</date>
    <debit>22.69</debit>
    <description>12/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV79</nr>
  </Movement>
  <Movement>
    <date>13/2/2013</date>
    <debit>48.20</debit>
    <description>13/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV80</nr>
  </Movement>
  <Movement>
    <date>14/2/2013</date>
    <debit>2.40</debit>
    <description>14/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV81</nr>
  </Movement>
  <Movement>
    <date>14/2/2013</date>
    <debit>49.95</debit>
    <description>14/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV82</nr>
  </Movement>
  <Movement>
    <date>18/2/2013</date>
    <debit>100.00</debit>
    <description>18/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV83</nr>
  </Movement>
  <Movement>
    <date>21/2/2013</date>
    <debit>267.21</debit>
    <description>21/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV87</nr>
  </Movement>
</Account>

=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/xml/Accountings/Thuis 2013/Accounts/Netto Dara.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="../../../../xsl/Account2xml.xsl"?>
<!DOCTYPE Account SYSTEM "../../../../dtd/Account.dtd">
<Account>
  <Movement>
    <credit>456.56</credit>
    <date>3/1/2013</date>
    <description>3/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV12</nr>
  </Movement>
  <Movement>
    <credit>250.00</credit>
    <date>16/1/2013</date>
    <description>16/1/2013</description>
    <journal>Diversen</journal>
    <nr>DIV29</nr>
  </Movement>
  <Movement>
    <credit>664.32</credit>
    <date>4/2/2013</date>
    <description>4/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV64</nr>
  </Movement>
  <Movement>
    <credit>16.32</credit>
    <date>18/2/2013</date>
    <description>18/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV84</nr>
  </Movement>
  <Movement>
    <credit>100.00</credit>
    <date>19/2/2013</date>
    <description>19/2/2013</description>
    <journal>Diversen</journal>
    <nr>DIV85</nr>
  </Movement>
</Account>
