=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/dtd/Balance.dtd
<!ELEMENT Balance (LeftName,LeftResultName,LeftTotalName,LeftTypes,RightName,RightResultName,RightTotalName,RightTypes,name,BalanceLine*)>
<!ELEMENT BalanceLine (amount1?,amount2?,name1?,name2?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT LeftName (#PCDATA)>
<!ELEMENT RightName (#PCDATA)>
<!ELEMENT LeftTotalName (#PCDATA)>
<!ELEMENT RightTotalName (#PCDATA)>
<!ELEMENT LeftResultName (#PCDATA)>
<!ELEMENT RightResultName (#PCDATA)>
<!ELEMENT LeftTypes (#PCDATA)>
<!ELEMENT RightTypes (#PCDATA)>
<!ELEMENT name1 (#PCDATA)>
<!ELEMENT amount1 (#PCDATA)>
<!ELEMENT amount2 (#PCDATA)>
<!ELEMENT name2 (#PCDATA)>

=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/xml/Accountings/Thuis 2016/Balances/RelationsBalance.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Balance SYSTEM "../../../../dtd/Balance.dtd">
<Balance>
  <RightTypes>Debit</RightTypes>
  <name>RelationsBalance</name>
  <LeftTotalName>TOTAL FUNDS</LeftTotalName>
  <LeftResultName>REMAINING FUND</LeftResultName>
  <RightTotalName>TOTAL DEBTS</RightTotalName>
  <LeftName>Funds from customers</LeftName>
  <RightName>Debts to Suppliers</RightName>
  <LeftTypes>Credit</LeftTypes>
  <RightResultName>REMAINING DEBT</RightResultName>
  <BalanceLine>
    <amount2>220.00</amount2>
    <name2>Bunrot</name2>
  </BalanceLine>
  <BalanceLine>
    <amount2>243896.87</amount2>
    <name2>Hypotheek</name2>
  </BalanceLine>
  <BalanceLine>
    <amount2>4581.28</amount2>
    <name2>Lening Tay</name2>
  </BalanceLine>
  <BalanceLine>
    <amount2>3004.74</amount2>
    <name2>Lening Verbouwing</name2>
  </BalanceLine>
  <BalanceLine>
    <amount2>10400.00</amount2>
    <name2>Schulden aan ma</name2>
  </BalanceLine>
  <BalanceLine>
    <amount2>656.14</amount2>
    <name2>VISA</name2>
  </BalanceLine>
</Balance>
