=== DavidCADanneels/Accounting/BasicAccounting/src/main/resources/dtd/Journals.dtd
<!ELEMENT Journals (name, Journal*,CurrentObject?)>
<!ELEMENT Journal (abbr,name,type)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT abbr (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT CurrentObject (#PCDATA)>

=== DavidCADanneels/Accounting/BasicAccounting/src/test/resources/xml/Accountings/Thuis 2014/Journals.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Journals SYSTEM "../../../dtd/Journals.dtd">
<Journals>
  <name>Journals</name>
  <Journal>
    <abbr>DIV</abbr>
    <name>Diversen</name>
    <type>default</type>
  </Journal>
  <Journal>
    <abbr>TAY</abbr>
    <name>Tay</name>
    <type>default</type>
  </Journal>
  <Journal>
    <abbr>TRF</abbr>
    <name>Transfer</name>
    <type>default</type>
  </Journal>
    <CurrentObject>Diversen</CurrentObject>
</Journals>
